# Copyright (C) 2014 OmniROM Project
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is the device-specific product definition file for
# crespo. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that crespo is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.

# These are the hardware-specific configuration files
DEVICE_PACKAGE_OVERLAYS += \
	device/samsung/wave/overlay

# We have FFC
PRODUCT_COPY_FILES += \
	frameworks/native/data/etc/android.hardware.camera.front.xml:system/etc/permissions/android.hardware.camera.front.xml

# These are the hardware-specific configuration files
PRODUCT_COPY_FILES := \
	device/samsung/wave/prebuilt/asound.conf:system/etc/asound.conf \
	device/samsung/wave/libaudio/audio_policy.conf:system/etc/audio_policy.conf \
	device/samsung/wave/prebuilt/nvram_net_s8500.txt:system/vendor/firmware/nvram_net_s8500.txt \
	device/samsung/wave/prebuilt/nvram_net_s8530.txt:system/vendor/firmware/nvram_net_s8530.txt \
	device/samsung/wave/prebuilt/bcm4329_s8500.hcd:system/vendor/firmware/bcm4329_s8500.hcd \
	device/samsung/wave/prebuilt/bcm4329_s8530.hcd:system/vendor/firmware/bcm4329_s8530.hcd \
	device/samsung/wave/prebuilt/setmodel.sh:system/bin/setmodel.sh \

# Init files
PRODUCT_COPY_FILES += \
	device/samsung/wave/init.wave.rc:root/init.wave.rc \
	device/samsung/wave/init.wave2.rc:root/init.wave2.rc \
	device/samsung/wave/init.wave.usb.rc:root/init.wave.usb.rc \
	device/samsung/wave/init.recovery.wave.rc:root/init.recovery.wave.rc \
	device/samsung/wave/init.recovery.wave2.rc:root/init.recovery.wave2.rc \
	device/samsung/wave/init.wave.usb.rc:recovery/root/usb.rc \
	device/samsung/wave/fstab.wave:root/fstab.wave \
	device/samsung/wave/fstab.wave:root/fstab.wave2 \
	device/samsung/wave/ueventd.wave.rc:root/ueventd.wave.rc \
	device/samsung/wave/ueventd.wave.rc:root/ueventd.wave2.rc \
	device/samsung/wave/twrp.fstab:recovery/root/etc/twrp.fstab\
	device/samsung/wave/partition.sh:recovery/root/partition.sh

# Keylayout and Keychars
PRODUCT_COPY_FILES += \
	device/samsung/wave/prebuilt/usr/idc/mxt224_ts_input.idc:system/usr/idc/mxt224_ts_input.idc \
	device/samsung/wave/prebuilt/usr/keylayout/sec_jack.kl:system/usr/keylayout/sec_jack.kl \
	device/samsung/wave/prebuilt/usr/keylayout/s5pv210-keypad.kl:system/usr/keylayout/s5pv210-keypad.kl \
	device/samsung/wave/prebuilt/usr/keylayout/gpio-keys.kl:system/usr/keylayout/gpio-keys.kl \
	device/samsung/wave/prebuilt/usr/keychars/s5pv210-keypad.kcm:system/usr/keychars/s5pv210-keypad.kcm \
	device/samsung/wave/prebuilt/usr/keychars/sec_jack.kcm:system/usr/keychars/sec_jack.kcm \
	device/samsung/wave/prebuilt/usr/keychars/gpio-keys.kcm:system/usr/keychars/gpio-keys.kcm

# SHP Modem interfaces
PRODUCT_PACKAGES := \
	libmocha-ril

# Filesystem management tools
PRODUCT_PACKAGES += \
	setup_fs

# Usb accessory
PRODUCT_PACKAGES += \
	com.android.future.usb.accessory

# These are the OpenMAX IL configuration files
PRODUCT_COPY_FILES += \
	hardware/samsung/exynos3/s5pc110/sec_mm/sec_omx/sec_omx_core/secomxregistry:system/etc/secomxregistry \
	device/samsung/wave/prebuilt/media_profiles.xml:system/etc/media_profiles.xml \
	device/samsung/wave/prebuilt/media_codecs.xml:system/etc/media_codecs.xml \
	frameworks/av/media/libstagefright/data/media_codecs_google_audio.xml:system/etc/media_codecs_google_audio.xml \
	frameworks/av/media/libstagefright/data/media_codecs_google_telephony.xml:system/etc/media_codecs_google_telephony.xml \
	frameworks/av/media/libstagefright/data/media_codecs_google_video_le.xml:system/etc/media_codecs_google_video_le.xml

# These are the OpenMAX IL modules
PRODUCT_PACKAGES += \
	libSEC_OMX_Core \
	libOMX.SEC.AVC.Decoder \
	libOMX.SEC.M4V.Decoder \
	libOMX.SEC.M4V.Encoder \
	libOMX.SEC.AVC.Encoder

# Misc other modules
PRODUCT_PACKAGES += \
	lights.wave \
	sensors.wave \
	power.s5pc110 \
	hwcomposer.s5pc110 \
	camera.wave \
	gps.wave \
	audio.primary.wave \
	audio.a2dp.default \
	libril-client \
	libs3cjpeg

# Wi-Fi
PRODUCT_PACKAGES += \
	libwpa_client \
	hostapd \
	hostapd_default.conf \
	dhcpcd.conf \
	wpa_supplicant \
	wpa_supplicant.conf

# PVR
PRODUCT_PACKAGES += \
	libEGL_POWERVR \
	pvrsrvinit

# Libs
PRODUCT_PACKAGES += \
	libstagefrighthw

# Bluetooth MAC Address
PRODUCT_PACKAGES += \
	bdaddr_read

# Device-specific packages
PRODUCT_PACKAGES += \
	DeviceSettings \
	OmniTorch

# f2fs
PRODUCT_PACKAGES += \
	fsck.f2fs \
	mkfs.f2fs \
	fibmap.f2fs

# These are the hardware-specific features
PRODUCT_COPY_FILES += \
	frameworks/native/data/etc/handheld_core_hardware.xml:system/etc/permissions/handheld_core_hardware.xml \
	frameworks/native/data/etc/android.hardware.camera.flash-autofocus.xml:system/etc/permissions/android.hardware.camera.flash-autofocus.xml \
	frameworks/native/data/etc/android.hardware.telephony.gsm.xml:system/etc/permissions/android.hardware.telephony.gsm.xml \
	frameworks/native/data/etc/android.hardware.location.xml:system/etc/permissions/android.hardware.location.xml \
	frameworks/native/data/etc/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
	frameworks/native/data/etc/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
	frameworks/native/data/etc/android.hardware.sensor.proximity.xml:system/etc/permissions/android.hardware.sensor.proximity.xml \
	frameworks/native/data/etc/android.hardware.sensor.accelerometer.xml:system/etc/permissions/android.hardware.sensor.accelerometer.xml \
	frameworks/native/data/etc/android.hardware.sensor.compass.xml:system/etc/permissions/android.hardware.sensor.compass.xml \
	frameworks/native/data/etc/android.hardware.touchscreen.multitouch.jazzhand.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
	frameworks/native/data/etc/android.software.sip.voip.xml:system/etc/permissions/android.software.sip.voip.xml \
	frameworks/native/data/etc/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \

# The OpenGL ES API level that is natively supported by this device.
# This is a 16.16 fixed point number
PRODUCT_PROPERTY_OVERRIDES := \
	ro.opengles.version=131072 \
	debug.hwui.render_dirty_regions=false \
	ro.hwui.r_buffer_cache_size=1 \
	ro.hwui.layer_cache_size=8 \
	ro.hwui.path_cache_size=2 \
	ro.hwui.drop_shadow_cache_size=1 \
	ro.hwui.shape_cache_size=0.5 \
	ro.hwui.texture_cache_size=12 \
	ro.zygote.disable_gl_preload=true

# These are the hardware-specific settings that are stored in system properties.
# Note that the only such settings should be the ones that are too low-level to
# be reachable from resources or other mechanisms.
PRODUCT_PROPERTY_OVERRIDES += \
	persist.sys.media.legacy-drm=1 \
	wifi.interface=wlan0 \
	mobiledata.interfaces=pdp0,eth0,gprs,ppp0 \
	rild.libpath=/system/lib/libmocha-ril.so \
	ro.telephony.ril.config=signalstrength \
	ro.ril.hsxpa=1 \
	ro.ril.hsdpa.category=8 \
	ro.ril.hsupa.category=6 \
	ro.ril.gprsclass=10 \
	ro.ril.enable.amr.wideband=1 \
	ro.sf.lcd_density=240 \
	ro.bq.gpu_to_cpu_unsupported=1 \
	ro.config.low_ram=true \
	ro.telephony.call_ring.delay=0 \
	debug.composition.type=dyn \
	pm.sleep_mode=1 \
	persist.sys.force_highendgfx=true \
	persist.sys.purgeable_assets=1

PRODUCT_PROPERTY_OVERRIDES += \
	camera2.portability.force_api=1 \
	camera2.port.operation_time_ms=5000

# SGX540 is slower with the scissor optimization enabled
PRODUCT_PROPERTY_OVERRIDES += \
	ro.hwui.disable_scissor_opt=true

# enable Google-specific location features,
# like NetworkLocationProvider and LocationCollector
PRODUCT_PROPERTY_OVERRIDES += \
	ro.com.google.locationfeatures=1 \
	ro.com.google.networklocation=1

# We have sacrificed /cache for a larger /system, so it's not large enough for dalvik cache
PRODUCT_PROPERTY_OVERRIDES += \
    	dalvik.vm.dexopt-data-only=1

# Extended JNI checks
# The extended JNI checks will cause the system to run more slowly, but they can spot a variety of nasty bugs 
# before they have a chance to cause problems.
# Default=true for development builds, set by android buildsystem.
PRODUCT_PROPERTY_OVERRIDES += \
    	ro.kernel.android.checkjni=0 \
    	dalvik.vm.checkjni=false

# Strict mode disabled
PRODUCT_PROPERTY_OVERRIDES += \
    persist.sys.strictmode.disable=1 \
    persist.sys.strictmode.visual=0

# ART parameters
PRODUCT_PROPERTY_OVERRIDES += \
    	dalvik.vm.dex2oat-filter=interpret-only \
    	dalvik.vm.image-dex2oat-filter=speed \
    	dalvik.vm.dexopt-flag=o=y,m=y \
    	dalvik.vm.dex2oat-flags=--no-watch-dog

PRODUCT_DEX_PREOPT_DEFAULT_FLAGS := \
    	--compiler-filter=interpret-only

# Force dex2oat to not use swap file
PRODUCT_PROPERTY_OVERRIDES += \
    	dalvik.vm.dex2oat-swap=false

# Reduce background apps limit to 12 on low-tier devices
PRODUCT_PROPERTY_OVERRIDES += \
    	ro.sys.fw.bg_apps_limit=8

# Set max background services
PRODUCT_PROPERTY_OVERRIDES += \
    	ro.config.max_starting_bg=6

# Set default USB interface and default to internal SD as /sdcard
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += \
    	persist.sys.usb.config=mtp

include frameworks/native/build/phone-hdpi-dalvik-heap.mk

$(call add-product-dex-preopt-module-config,services,--compiler-filter=speed)

$(call inherit-product-if-exists, hardware/broadcom/wlan/bcmdhd/firmware/bcm4329/device-bcm.mk)

# See comment at the top of this file. This is where the other
# half of the device-specific product definition file takes care
# of the aspects that require proprietary drivers that aren't
# commonly available
$(call inherit-product-if-exists, vendor/samsung/wave/wave-vendor.mk)
